appname: test
port: 8088

db:
  name:     admin_test
  user:     root
  password: root
  port:     3306
  host:     127.0.0.1
  maxIdleConns: 5
  maxOpenConns: 10

memDB:
  name: one

contacts:
  - name: i test
    email: test@test.com