appname: test
port: 8088

host: http://gugong.demoto.cn

db:
  name:     hyzx
  user:     root
  password: root
  port:     3306
  host:     127.0.0.1
  maxIdleConns: 5
  maxOpenConns: 10

memDB:
  name: one

wx:
  appID:  wx54175bbcec40ae45
  appSecret:  ed8803049662b0d8fdb6f6b56074d46a
  token:  4NHuXDxABeNvycENLoysTTzD
  encodingAESKey: